#!/bin/bash
#$ -pe openmpi 1 
#$ -l h_rt=2:15:00
#$ -N ppcg_63_64_64_161e3_pm_1e6_cpu_ilu01_excpt_al
#$ -cwd

APP=./dpcg_precon
# ARGS="../../../dimitar_tsts_dec2013/AC32_8bub_sd.mtx  ../../../dimitar_tsts_dec2013/x_readin32_8bub_sd.rec ../../../dimitar_tsts_dec2013/b_readin32_8bub_sd.rec 8"
ARGS="../../../convert_coo_to_mm/a_63_16_1e3.mtx ../../../convert_coo_to_mm/Z_63_16_1e3.mtx ../../../convert_coo_to_mm/r_63_16_1e3.dat 8"
#ARGS="../../../convert_coo_to_mm/atry1_3.mtx  ../../../convert_coo_to_mm/r_3.dat 8"
# Get OpenMPI settings
. /etc/bashrc
module load openmpi/gcc
module load cuda55/toolkit cuda55/profiler cuda55/blas
# Make new hostfile specifying the cores per node wanted
ncores=1
HOSTFILE=$TMPDIR/hosts
for host in `uniq $TMPDIR/machines`; do
    echo $host slots=$ncores
    done > $HOSTFILE
    nhosts=`wc -l < $HOSTFILE`
    totcores=`expr $nhosts \* $ncores`

# Use regular ssh-based startup instead of OpenMPI/SGE native one
unset PE_HOSTFILE
PATH=/usr/bin:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/ROHIT/babysteps/paralution-0.5.0/build/lib
$MPI_RUN -np $totcores --hostfile $HOSTFILE $APP $ARGS
